{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run lint"
				}
			]
		},
		"build": {
			"strategy": {
				"matrix": {
					"os": ["ubuntu-latest", "macos-latest", "windows-latest"]
				}
			},
			"runs-on": "${{ matrix.os }}",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run publish"
				}
			]
		},
		"test": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run test"
				}
			]
		},
		"npx": {
			"strategy": {
				"matrix": {
					"os": ["ubuntu-latest", "macos-latest", "windows-latest"]
				}
			},
			"runs-on": "${{ matrix.os }}",
			"steps": [
				{
					"run": "npx brianjenkins94/prev -y"
				},
				{
					"uses": "./",
					"with": {
						"start": "npm run cypress",
						"wait-on": "http://localhost:3000"
					}
				}
			]
		}
	}
}
